// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCas0oopv43d9guDa0v88EifYdBXoMYhU0',
    appId: '1:67490601705:web:3da570e9e516253c046e78',
    messagingSenderId: '67490601705',
    projectId: 'remote-control-app-d69ad',
    authDomain: 'remote-control-app-d69ad.firebaseapp.com',
    storageBucket: 'remote-control-app-d69ad.appspot.com',
    measurementId: 'G-DEQ7V8HM1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLQZdpt4yV1aGLRvt91RFLMibzr7WXsY8',
    appId: '1:67490601705:android:dd236592d5f5d48f046e78',
    messagingSenderId: '67490601705',
    projectId: 'remote-control-app-d69ad',
    storageBucket: 'remote-control-app-d69ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD61TD-ZmlIgqaC2RhI-nNL0jdAfeNZ5IE',
    appId: '1:67490601705:ios:7f3ba970121b16cb046e78',
    messagingSenderId: '67490601705',
    projectId: 'remote-control-app-d69ad',
    storageBucket: 'remote-control-app-d69ad.appspot.com',
    iosBundleId: 'com.example.remoteControlApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCas0oopv43d9guDa0v88EifYdBXoMYhU0',
    appId: '1:67490601705:web:26b6b03ebdb96817046e78',
    messagingSenderId: '67490601705',
    projectId: 'remote-control-app-d69ad',
    authDomain: 'remote-control-app-d69ad.firebaseapp.com',
    storageBucket: 'remote-control-app-d69ad.appspot.com',
    measurementId: 'G-LENT06RP75',
  );
}
